# Generated by Django 5.0.3 on 2024-03-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_alter_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='author',
            new_name='user',
        ),
    ]
